#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Aug 09 17:54:58 -04 2024
# SW Build 2188600 on Wed Apr  4 18:39:19 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim ALU_tb_behav -key {Behavioral:sim_1:Functional:ALU_tb} -tclbatch ALU_tb.tcl -view /home/lgomez/Documentos/MAGISTER_UBA/Bimestre05/FPGA/Proyecto_FINAL/ProyectoALU_vivado/Proyecto_ALU/ALU_tb_behav.wcfg -view /home/lgomez/Documentos/MAGISTER_UBA/Bimestre05/FPGA/Proyecto_FINAL/ProyectoALU_vivado/Proyecto_ALU/ALU_time_impl.wcfg -log simulate.log
